"use client";
import { FormEvent, useState } from "react";
import { useMutation } from "@tanstack/react-query";
import { forecastApi } from "@/services/api/domain";
import { PageHeading } from "@/components/common/page-heading";
import { useLanguage } from "@/i18n/language";

export default function ForecastPage() { const { text } = useLanguage(); const [horizon,setHorizon]=useState(5); const [model,setModel]=useState("exponential"); const m=useMutation({mutationFn:()=>forecastApi.create({symbol:"AU0",horizon,model})}); const submit=(e:FormEvent)=>{e.preventDefault();m.mutate()}; return <div><PageHeading eyebrow="MODEL ESTIMATE" title={text("黄金价格预测", "Gold Price Forecast")} description={text("基线模型输出与历史评估分开呈现，不把启发式评分描述为真实概率。", "Baseline outputs are separated from historical evaluation; heuristic scores are not presented as real probabilities.")}/><form onSubmit={submit} className="card grid gap-4 p-5 sm:grid-cols-3"><label className="text-sm">{text("预测周期", "Forecast horizon")}<input type="number" min={1} max={30} value={horizon} onChange={e=>setHorizon(Number(e.target.value))} className="mt-2 w-full rounded border border-line bg-canvas p-2"/></label><label className="text-sm">{text("模型", "Model")}<select value={model} onChange={e=>setModel(e.target.value)} className="mt-2 w-full rounded border border-line bg-canvas p-2"><option value="exponential">Exponential</option><option value="linear">Linear</option><option value="ma">Moving Average</option></select></label><button className="mt-6 rounded bg-gold p-2 font-medium text-black">{text("运行预测", "Run forecast")}</button></form>{m.isError&&<p className="mt-4 text-negative">{m.error.message}</p>}{m.data&&<section className="card mt-5 p-5"><div className="grid gap-3 sm:grid-cols-4"><Metric label={text("当前价", "Current price")} value={m.data.current_price.toFixed(2)}/><Metric label="MAE" value={m.data.metrics.mae?.toFixed(2)??"—"}/><Metric label="RMSE" value={m.data.metrics.rmse?.toFixed(2)??"—"}/><Metric label={text("方向准确率", "Direction accuracy")} value={m.data.metrics.direction_accuracy==null?"—":`${(m.data.metrics.direction_accuracy*100).toFixed(1)}%`}/></div><h2 className="mt-6 font-medium">{text("预测路径", "Forecast path")}</h2><div className="mt-3 flex flex-wrap gap-2">{m.data.predicted_prices.map((p:number,i:number)=><div key={i} className="rounded border border-line px-3 py-2 tabular">T+{i+1} · {p.toFixed(2)}</div>)}</div><p className="mt-5 text-sm text-warning">{m.data.disclaimer}</p></section>}</div>; }
function Metric({label,value}:{label:string;value:string}){return <div className="rounded-lg bg-canvas p-3"><div className="text-xs text-muted">{label}</div><div className="tabular mt-1 text-lg">{value}</div></div>}
