"use client";
import { useQuery } from "@tanstack/react-query";
import { marketApi } from "@/services/api/market";
import { GoldChart } from "@/components/charts/gold-chart";
import { PageHeading } from "@/components/common/page-heading";
import { ErrorState, LoadingState } from "@/components/common/async-state";
import { SourceBadge } from "@/components/common/source-badge";
import { useLanguage } from "@/i18n/language";

export default function AnalysisPage() { const { text } = useLanguage(); const q = useQuery({ queryKey: ["analysis"], queryFn: async () => ({ history: await marketApi.history(800), technical: await marketApi.indicators() }) }); if (q.isLoading) return <LoadingState label={text("正在计算技术指标", "Calculating technical indicators")}/>; if (!q.data || q.isError) return <ErrorState message={(q.error as Error)?.message ?? text("分析不可用", "Analysis unavailable")}/>; const t=q.data.technical; const provisional=q.data.history.points.at(-1)?.is_provisional; return <div><PageHeading eyebrow="TECHNICAL ANALYSIS" title={text("黄金技术分析", "Gold Technical Analysis")} description={text("指标使用已完成周期的数据计算；来源、推导状态与更新时间始终可见。", "Indicators use completed periods; source, derivation status, and retrieval time remain visible.")}/><div className="mb-4 flex justify-end"><SourceBadge source={t.metadata}/></div><div className="card p-4">{provisional&&<p className="mb-3 rounded-lg border border-gold/30 bg-gold/5 p-3 text-sm text-gold">{text(`金色 K 线是交易日 ${q.data.history.points.at(-1)?.timestamp.slice(0,10)} 的进行中行情；技术指标截至 ${t.timestamp.slice(0,10)}，收盘 ${t.close.toFixed(2)}。`, `The gold candle is the in-progress session for ${q.data.history.points.at(-1)?.timestamp.slice(0,10)}. Indicators use completed data through ${t.timestamp.slice(0,10)} at a ${t.close.toFixed(2)} close.`)}</p>}<GoldChart points={q.data.history.points}/></div><div className="mt-4 grid gap-3 md:grid-cols-3"><div className="card p-4"><div className="text-xs text-muted">{text("趋势", "Trend")}</div><div className="mt-2 text-xl">{t.trend}</div></div><div className="card p-4"><div className="text-xs text-muted">{text("支撑 / 阻力", "Support / Resistance")}</div><div className="tabular mt-2 text-xl">{t.support?.toFixed(2)} / {t.resistance?.toFixed(2)}</div></div><div className="card p-4"><div className="text-xs text-muted">{text("数据质量", "Data quality")}</div><div className="mt-2 text-sm">{t.metadata.is_derived ? text("推导行情，请谨慎解释", "Derived market data; interpret carefully") : text("直接市场源", "Direct market source")}</div></div></div></div>; }
