"use client";
import { FormEvent, useState } from "react";
import { useMutation, useQuery } from "@tanstack/react-query";
import { backtestApi } from "@/services/api/domain";
import { PageHeading } from "@/components/common/page-heading";
import { useLanguage } from "@/i18n/language";

export default function BacktestPage(){const { text }=useLanguage();const [id,setId]=useState<string|null>(null);const [short,setShort]=useState(5);const [long,setLong]=useState(20);const create=useMutation({mutationFn:()=>backtestApi.create({strategy:"ma_cross",initial_capital:100000,transaction_cost_rate:0.0015,parameters:{short_window:short,long_window:long}}),onSuccess:d=>setId(d.id)});const result=useQuery({queryKey:["backtest",id],queryFn:()=>backtestApi.get(id!),enabled:!!id,refetchInterval:q=>q.state.data?.status==="completed"||q.state.data?.status==="failed"?false:1500});const submit=(e:FormEvent)=>{e.preventDefault();create.mutate()};const r=result.data?.result;return <div><PageHeading eyebrow="NO LOOK-AHEAD" title={text("策略回测", "Strategy Backtest")} description={text("信号在下一周期执行，并计入交易成本；结果与买入持有基准对比。", "Signals execute in the next period with transaction costs and are compared against buy-and-hold.")}/><form onSubmit={submit} className="card flex flex-wrap items-end gap-4 p-5"><label className="text-sm">{text("短均线", "Short MA")}<input type="number" value={short} onChange={e=>setShort(Number(e.target.value))} className="mt-2 block w-28 rounded border border-line bg-canvas p-2"/></label><label className="text-sm">{text("长均线", "Long MA")}<input type="number" value={long} onChange={e=>setLong(Number(e.target.value))} className="mt-2 block w-28 rounded border border-line bg-canvas p-2"/></label><button className="rounded bg-gold px-5 py-2 text-black">{text("运行回测", "Run backtest")}</button></form>{id&&<p className="my-4 text-sm text-muted">{text("任务", "Job")} {id} · {result.data?.status??"queued"}</p>}{result.data?.error&&<p className="text-negative">{result.data.error}</p>}{r&&<div><section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{Object.entries(r.metrics).map(([k,v])=><Metric key={k} label={k} value={typeof v==="number"?v.toFixed(4):String(v)}/>)}</section><section className="card mt-4 overflow-x-auto p-4"><h2 className="mb-3 font-medium">{text("交易记录", "Trades")}</h2><table className="w-full text-left text-sm"><thead className="text-muted"><tr><th>{text("时间", "Time")}</th><th>{text("动作", "Action")}</th><th>{text("价格", "Price")}</th><th>{text("成本", "Cost")}</th><th>PnL</th></tr></thead><tbody>{r.trades.map((t:any,i:number)=><tr key={i} className="border-t border-line"><td className="py-2">{t.timestamp.slice(0,10)}</td><td>{t.action}</td><td>{t.price.toFixed(2)}</td><td>{t.cost.toFixed(2)}</td><td>{t.pnl?.toFixed(2)??"—"}</td></tr>)}</tbody></table></section></div>}</div>}
function Metric({label,value}:{label:string;value:string}){return <div className="card p-4"><div className="text-xs text-muted">{label}</div><div className="tabular mt-2 text-xl">{value}</div></div>}
